name: home
publish_to: none

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  core:
    path: ../../core
  flutter:
    sdk: flutter

  provider: ^6.0.5
  responsive_framework: ^0.2.0
  smooth_page_indicator: ^1.0.0+2
  sprung: ^3.0.1
  very_good_analysis: ^5.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
    - assets/screenshot/alterra/
    - assets/screenshot/budget-intelli/
    - assets/screenshot/dana/
    - assets/screenshot/ebook/
    - assets/screenshot/food_app/
    - assets/screenshot/saving/
    - assets/screenshot/telkomsel/
    - assets/screenshot/tempat_makan/
    - assets/screenshot/pln/
    - assets/screenshot/udemy/
    - assets/screenshot/barista/
    - assets/screenshot/pln_click/
    - assets/screenshot/colok_in/
    - assets/certificate_img/
    - assets/certificate_img/javascript/
    - assets/certificate_img/backend/
    - assets/certificate_img/aws/
