name: home
publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../../core
  responsive_framework: ^0.2.0
  provider: ^6.0.5
  sprung: ^3.0.1
  smooth_page_indicator: ^1.0.0+2
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
    - assets/screenshot/alterra/
    - assets/screenshot/dana/
    - assets/screenshot/ebook/
    - assets/screenshot/food_app/
    - assets/screenshot/saving/
    - assets/screenshot/telkomsel/
    - assets/screenshot/tempat_makan/
    - assets/screenshot/pln/
    - assets/certificate_img/
    - assets/certificate_img/javascript/
    - assets/certificate_img/backend/
    - assets/certificate_img/aws/