name: web_portfolio
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.0.4
  go_router: ^14.1.4
  google_fonts: ^5.0.0
  provider: ^6.0.5
  responsive_framework: ^0.2.0
  smooth_page_indicator: ^1.0.0+2
  sprung: ^3.0.1
  url_launcher: ^6.1.7
  very_good_analysis: ^5.1.0
  

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/screenshot/alterra/
    - assets/screenshot/budget-intelli/
    - assets/screenshot/dana/
    - assets/screenshot/ebook/
    - assets/screenshot/food_app/
    - assets/screenshot/saving/
    - assets/screenshot/telkomsel/
    - assets/screenshot/tempat_makan/
    - assets/screenshot/pln/
    - assets/screenshot/udemy/
    - assets/screenshot/barista/
    - assets/screenshot/pln_click/
    - assets/screenshot/colok_in/
    - assets/certificate_img/
    - assets/certificate_img/javascript/
    - assets/certificate_img/backend/
    - assets/certificate_img/aws/
