name: web_portfolio
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  core:
    path: packages/core
  home:
    path: packages/features/home
  responsive_framework: ^0.2.0
  go_router: ^14.1.4
  provider: ^6.0.5
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
