name: core
publish_to: none

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.0.4
  google_fonts: ^5.0.0
  responsive_framework: ^0.2.0
  url_launcher: ^6.1.7
  very_good_analysis: ^5.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
